[package]
name = "rust_diary"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
time = { version = "0.3.37", features = ["formatting"] }
ratatui = { version = "0.29.0", features = ["all-widgets"] }
